theme = "minos"
baseURL = "https://ifnull.org/"
languageCode = "en-us"
title = "M"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  DisqusShortname = "ifnull"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = -100

  [[menu.main]]
    name = "Projects"
    url = "/projects/all/"
    weight = -80

  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = -60

  [[menu.main]]
    name = "Mabsurdation"
    url = "/mabsurdation/"
    weight = -50

  [[menu.main]]
    name = "Gallery"
    url = "/gallery/public/"
    weight = -45

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = -40
